import_now:
  fields:
    config_entry_id:
      required: false
      example: 1a2b3c4d5e6f7g8h9i0j
      selector:
        config_entry:
          integration: eso
    date_from:
      required: false
      example: "2026-01-01"
      selector:
        date:
    date_to:
      required: false
      example: "2026-07-16"
      selector:
        date:
